### ISSUE TITLE
[feature] Lodash upgrade

### ISSUE THREAD

**Issue by FernandoMorais** [pawelgalazka/cli#3]
Hi @pawelgalazka!

Since Jun 19th versions of lodash before 4.17.12 was reported with a high severity vulnerability.
More info here: https://npmjs.com/advisories/1065  

Some packages on our solutions depends on @pawelgalazka/cli and I'd like to know if could you update lodash or if I can start a PR to help you out.

Thanks in advance!

**Comment by Riplar** [comment]
@pawelgalazka 
Experiencing the same issue and would really appreciate an update to >=4.17.12.

**Comment by PineSongCN** [comment]
+1

**Comment by FernandoMorais** [comment]
@pawelgalazka 
Could you take a look ar this?

**Comment by gfernandez-me** [comment]
+1

**Comment by pawelgalazka** [comment]
done

**Comment by Riplar** [comment]
@pawelgalazka 
The same issue came up again:
https://www.npmjs.com/advisories/1523

So it would be great if you would update lodash to version 4.17.19 or higher.
